dyc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: material_database
    username: root
    password: a489732962
  mongodb:
    uri: mongodb://mongo:mongo@localhost:27017/test?authSource=admin
    database: test
    host: localhost
    port: 27017